### ISSUE TITLE
Linker paths

### ISSUE THREAD

**Issue by brucelane** [Allar/UE4ToSpout#2]
Hi,
Looking at this https://github.com/Allar/UE4ToSpout/blob/ea3803800ff3fc9940f65c8cd3f095535d9ff473/Engine/Source/ThirdParty/Spout/Spout.Build.cs#L29 it uses Spout.lib.
With latest Spout2 repo, the files are named Spout64.lib and Spout64.dll, could you update your repo?
If you need, I could do a pull request

**Comment by Allar** [comment]
Please make a pull request. I'll merge it in, and take a look afterward when I get back from my trip to Epic.

**Comment by ZimaXXX** [comment]
It seems that Spout came back to Spout.\* pattern, so now linker looks for Spout64.lib, there's none and linker fails.
If anyone has the same problem, just change the names of files to Spout32.\* and Spout64.*.

Another issue is that the Plugin itself needs Spout.dll and Editor will crash on start when enabled. I've solved it by copying and pasting Spout64.dll into the same folder and renaming back to Spout.dll.

So it concludes to: **you need both Spout64.dll/lib and Spout.dll !**
